services:
  postgres:
    container_name: postgres
    image: postgres:16
    environment:
      POSTGRES_USER: raghav
      POSTGRES_PASSWORD: password
      POSTGRES_DB: default
    volumes:
      - pg-data:/var/lib/postgresql/data

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    depends_on:
      - postgres
    ports:
      - "4000:4000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/prisma/migrations:/app/prisma/migrations

volumes:
  pg-data:
