services:
  postgres:
    container_name: postgres
    image: postgres:16
    environment:
      POSTGRES_USER: raghav
      POSTGRES_PASSWORD: password
      POSTGRES_DB: default
    volumes:
      - pg-data:/var/lib/postgresql/data

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    depends_on:
      - postgres
    ports:
      - "4000:4000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/prisma/migrations:/app/prisma/migrations
    develop:
      watch:
        - action: sync
          path: ./backend
          target: /app
          ignore:
            - node_modules/
            - prisma/migrations/
        - action: rebuild
          path: ./backend/package.json
        - action: rebuild
          path: ./backend/.env
        - action: rebuild
          path: ./backend/prisma/schema.prisma

  prisma-studio:
    image: node:20-alpine
    container_name: prisma-studio
    working_dir: /app
    volumes:
      - ./backend:/app
    command: sh -c "npx prisma studio"
    ports:
      - "51212:51212"
    depends_on:
      - backend

volumes:
  pg-data:
